### ISSUE TITLE
How to migration database

### ISSUE THREAD

**Issue by Pedroxam** [octobercms/docs#379]
Hello,

after i enter database details to database.php, now i want import database.

but "php artisan migration" not work"

how can i import database ?

**Comment by LukeTowers** [comment]
If you want to setup a new database by running your migrations, run `php artisan october:up`. If you want to import an existing database, use whatever tool you typically use to manage your databases. 

Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by Pedroxam** [comment]
Thanks @LukeTowers , i read the documents on "https://octobercms.com/forum", and i will never find my answer. anyway , my problem now is fixed, thanks.
