### ISSUE TITLE
Link doesn't exist

### ISSUE THREAD

**Issue by ghost** [octobercms/docs#392]
Go to this section: https://octobercms.com/docs/cms/pages/#page-variables

Click on the link: `this.page variable`

Goes to this web page: https://octobercms.com/docs/cms/markup/this-page

404 Error.

**Comment by w20k** [comment]
@ayumihamsaki works now:
https://octobercms.com/docs/markup/this-page

**Comment by ayumihamsaki** [comment]
haha thanks for the answer will create a pr for that:

```html
https://octobercms.com/docs/markup/this-page
https://octobercms.com/docs/cms/markup/this-page
```

- Two different URL's.

**Comment by w20k** [comment]
@ayumihamsaki try again, it's fixed for me ;)

Screenshot:
<img width="1287" alt="Screenshot 2019-08-08 at 16 30 43" src="https://user-images.githubusercontent.com/1053320/62707388-ed418480-b9f9-11e9-80a4-3bf6239c0426.png">

**Comment by ayumihamsaki** [comment]
@w20k 

I think it needs to be `../../` not `../`

**Comment by w20k** [comment]
@ayumihamsaki for me it works as expected. Don't see a reason to fix it :)

**Comment by ayumihamsaki** [comment]
@w20k 

`../` gives:

```html
https://octobercms.com/docs/cms/markup/this-page
```

`../../` gives:

```html
https://octobercms.com/docs/markup/this-page
```

**Comment by ayumihamsaki** [comment]
@w20k present for you: https://youtu.be/LlRRdSWopx4

**Comment by w20k** [comment]
@ayumihamsaki you definitely having some issue. 

https://octobercms.com/docs/markup/this-page

**Comment by LukeTowers** [comment]
@ayumihamsaki what's in your URL bar when you have that result before clicking the link? Tested it in Chrome, Firefox, & Safari on Mac OS and they all work fine.

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers No problem here is a screenshot:

![luke](https://user-images.githubusercontent.com/17784082/62823787-fd3d9d80-bb8c-11e9-9557-4356dbe1e375.png)

I don't want to sound rude, but I understand why you guys get one set of results and I get another - it's because browsers don't work exactly the same for every user. Is there a better way to test such problems because we could have 10 people saying they get your results and another 10 people saying their getting mine.

- Running Chrome Version 75.0.1000.0 on a PC with Windows 10
- Running Chrome Version 78.0.3879.0 on a PC with Windows 10
- Running Chrome Version 78.0.3879.0 on a PC with Windows 7
- Running Chrome Version 78.0.3879.0 on a MAC

All of these will give different results, I know that from speaking to the Chrome team.

**Comment by LukeTowers** [comment]
@ayumihamsaki Your URL is `cms/pages/`, however when I browse to `https://octobercms.com/docs/cms/pages/` I get automatically redirected to `https://octobercms.com/docs/cms/pages`. The issue is that you are not being redirected, or your browser is choosing to ignore that redirect. The official canonical URL for that page is `https://octobercms.com/docs/cms/pages`, which means that the URL as built right now is correct.

**Comment by ayumihamsaki** [comment]
@LukeTowers This is going to sound crazy but browsers and search engine bots ignore canonical URL's. I had a look chat about this with a Googler a few months ago. He told me they usually ignore them - which I was gutted when he said that.

Here's the test results for that link with any redirects:

![test](https://user-images.githubusercontent.com/17784082/62824143-baca8f80-bb91-11e9-8ed5-9beecc24e0d5.png)

Definetly not redirecting properly.

**Comment by LukeTowers** [comment]
that URL is incorrect, but testing `https://octobercms.com/docs/cms/pages/` for a redirect to `https://octobercms.com/docs/cms/pages` didn't trigger a redirect so this is an issue for the marketplace site to handle.

**Comment by daftspunk** [comment]
I think the tester might be broken

Below pulled straight from Chrome:
```
Request URL: https://octobercms.com/docs/cms/pages/
Request Method: GET
Status Code: 301 Moved Permanently
Location: http://octobercms.com/docs/cms/pages
```

**Comment by LukeTowers** [comment]
@ayumi-cloud what's the latest on this?
